[package]
name = "host"
version = "0.0.1"
authors = ["mainrs"]
license = "UPL-1.0"
edition = "2018"
links = "app"

[profile.release]
lto = true
strip = "debuginfo"
codegen-units = 1

[lib]
name = "host"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib"]

[[bin]]
name = "host"
path = "src/main.rs"

[dependencies]
roc_std = { path = "glue/roc_std", features = ["std"] }
roc_app = { path = "glue/roc_app" }
# roc_fn = { path = "src/roc_fn" }
# glue_manual = { path = "src/glue_manual" }
libc = "0.2"
hyper = { version = "0.14", features = [
    "http1",
    "http2",
    "client",
    "server",
    "runtime",
    "backports",
    "deprecated",
] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = { version = "0.11.11", default-features = false, features = [
    "blocking",
    "rustls-tls",
] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
futures = "0.3"
backtrace = "0.3.68"
bytes = "1.0"

[workspace]
